name: flutkit
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  provider: ^4.1.2
  shared_preferences: ^2.0.3
  material_design_icons_flutter: ^4.0.5755
  charts_flutter: ^0.9.0
  google_fonts: ^1.1.0
  google_maps_flutter: ^0.5.28
  google_maps_flutter_web: ^0.1.0
  flutter_icons: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    #Profiles
    - assets/images/avatar.jpg
    - assets/images/avatar-1.jpg
    - assets/images/avatar-2.jpg
    - assets/images/avatar-3.jpg
    - assets/images/avatar-4.jpg
    - assets/images/avatar-5.jpg
    - assets/images/avatar-place.png
    - assets/images/profile-banner.jpg


    #Shopping
    - assets/images/shopping/headphone.jpg
    - assets/images/shopping/headphone-1.jpg
    - assets/images/shopping/art.jpg
    - assets/images/shopping/fashion.jpg
    - assets/images/shopping/lifestyle.jpg
    - assets/images/shopping/technology.jpg
    - assets/images/shopping/product/product-1.jpg
    - assets/images/shopping/product/product-2.jpg
    - assets/images/shopping/product/product-3.jpg
    - assets/images/shopping/product/product-4.jpg
    - assets/images/shopping/product/product-5.jpg
    - assets/images/shopping/product/product-6.jpg
    - assets/images/shopping/product/product-7.jpg
    - assets/images/shopping/product/product-8.jpg
    - assets/images/shopping/product/product-9.jpg
    - assets/images/shopping/product/product-10.jpg
    - assets/images/shopping/product/product-11.jpg
    - assets/images/shopping/offer/offer-1.png
    - assets/images/shopping/offer/offer-2.png
    - assets/images/shopping/vector/dress.png
    - assets/images/shopping/vector/headphone.png
    - assets/images/shopping/vector/laptop.png
    - assets/images/shopping/vector/shoes.png
    - assets/images/shopping/vector/tshirt.png
    - assets/images/shopping/vector/watch.png
    - assets/images/shopping/vector/mobile.png
    - assets/images/shopping/camera/camera-1.jpg
    - assets/images/shopping/camera/camera-2.jpg
    - assets/images/shopping/camera/camera-3.jpg

    #Brand
    - assets/brand/flutkit.png
    - assets/brand/flutkit_icon.png
    - assets/brand/paypal.png
    - assets/brand/visa-card.png
    - assets/brand/master-card.png
    - assets/brand/google.png

    #Hotel
    - assets/images/hotel/hotel-1.jpg
    - assets/images/hotel/hotel-2.jpg
    - assets/images/hotel/room-1.jpg
    - assets/images/hotel/room-2.jpg
    - assets/images/hotel/room-3.jpg

    #Places
    - assets/images/place/cuba.jpg
    - assets/images/place/london.jpg
    - assets/images/place/paris.jpg

    #Music
    - assets/images/music/singer-1.jpg
    - assets/images/music/singer-2.jpg
    - assets/images/music/singer-3.jpg
    - assets/images/music/singer-4.jpg
    - assets/images/music/event-1.jpg
    - assets/images/music/event-2.jpg
    - assets/images/music/event-3.jpg
    - assets/images/music/all-1.jpg
    - assets/images/music/all-2.jpg
    - assets/images/music/all-l1.jpg
    - assets/images/music/all-l2.jpg
    - assets/images/music/all-l3.jpg
    - assets/images/music/podcast-1.jpg
    - assets/images/music/podcast-2.jpg
    - assets/images/music/podcast-3.jpg
    - assets/images/music/podcast-4.jpg

    #Food
    - assets/food/beverage-1.jpg
    - assets/food/beverage-2.jpg
    - assets/food/beverage-3.jpg
    - assets/food/burger-1.jpg
    - assets/food/burger-2.jpg
    - assets/food/burger-3.jpg
    - assets/food/dessert-1.jpg
    - assets/food/dessert-2.jpg
    - assets/food/dessert-3.jpg
    - assets/food/dessert-4.jpg
    - assets/food/food-1.jpg
    - assets/food/food-2.jpg
    - assets/food/food-3.jpg
    - assets/food/food-4.jpg
    - assets/food/food-5.jpg
    - assets/food/food-6.jpg
    - assets/food/food-7.jpg
    - assets/food/food-8.jpg
    - assets/food/food-9.jpg
    - assets/food/food-l1.jpg
    - assets/food/food-l2.jpg
    - assets/food/food-l3.jpg
    - assets/food/food-l4.jpg
    - assets/food/food-p1.jpg
    - assets/food/food-p2.jpg
    - assets/food/food-p3.jpg
    - assets/food/pasta-1.jpg
    - assets/food/restaurant.jpg

    #Course
    - assets/images/course/art.jpg
    - assets/images/course/biology.jpg
    - assets/images/course/class-l1.jpg
    - assets/images/course/craft.jpg
    - assets/images/course/robot.jpg
    - assets/images/course/subject-1.jpg
    - assets/images/course/subject-2.jpg
    - assets/images/course/subject-3.jpg
    - assets/images/course/subject-4.jpg
    - assets/images/course/subject-5.jpg
    - assets/images/course/subject-6.jpg

    #Chat
    - assets/images/chat/whatsapp-bg.jpg
    - assets/images/chat/video-bg-1.jpg
    - assets/images/chat/video-bg-2.jpg

    #Social
    - assets/images/social/post-1.jpg
    - assets/images/social/post-l1.jpg
    - assets/images/social/profile-p1.jpg

    #Other
    - assets/images/all/all-1.jpg
    - assets/images/all/all-2.jpg
    - assets/images/all/all-3.jpg
    - assets/images/all/all-4.jpg
    - assets/images/all/all-5.jpg
    - assets/images/all/all-6.jpg
    - assets/images/all/all-7.jpg
    - assets/images/all/all-8.jpg
    - assets/images/all/all-9.jpg
    - assets/images/all/all-10.jpg
    - assets/images/all/all-11.jpg
    - assets/images/all/all-12.jpg
    - assets/images/all/all-13.jpg
    - assets/images/all/all-14.jpg
    - assets/images/all/all-15.jpg
    - assets/images/all/all-l1.jpg
    - assets/images/all/all-l2.jpg
    - assets/images/all/all-l3.jpg
    - assets/images/all/all-p1.jpg
    - assets/images/all/all-p2.jpg
    - assets/images/all/all-p3.jpg


    ###################---------------------- Custom Apps -------------------------#################

    ##Grocery
    - assets/grocery/strawberry.png
    - assets/grocery/broccoli.png
    - assets/grocery/cheese.png
    - assets/grocery/bread.png
    - assets/grocery/product-1.png
    - assets/grocery/product-2.png
    - assets/grocery/product-3.png
    - assets/grocery/product-4.png
    - assets/grocery/product-5.png
    - assets/grocery/profile.png


    #Illustration
    - assets/illustration/food/illu-1.png
    - assets/illustration/food/illu-2.png
    - assets/illustration/food/illu-3.png
    - assets/illustration/shopping/illu-1.png
    - assets/illustration/shopping/illu-2.png
    - assets/illustration/shopping/illu-3.png
    - assets/illustration/shopping/order-confirm.png
    - assets/illustration/shopping/maintenance.png
    - assets/illustration/shopping/page-not-found.png
    - assets/illustration/shopping/empty-cart.png
    - assets/illustration/hotel/illu-1.png
    - assets/illustration/hotel/illu-2.png
    - assets/illustration/hotel/illu-3.png
    - assets/illustration/music/illu-1.png
    - assets/illustration/music/illu-2.png


    #Icons
    - assets/icons/albums-outline.png
    - assets/icons/analytics-outline.png
    - assets/icons/apps-outline.png
    - assets/icons/browsers-outline.png
    - assets/icons/code-outline.png
    - assets/icons/copy-outline.png
    - assets/icons/download-outline.png
    - assets/icons/ellipsis-vertical-circle-outline.png
    - assets/icons/ellipsis-vertical-outline.png
    - assets/icons/file-tray-full-outline.png
    - assets/icons/grid-outline.png
    - assets/icons/hourglass-outline.png
    - assets/icons/instagram-outline.png
    - assets/icons/list-outline.png
    - assets/icons/course-outline.png
    - assets/icons/planet-outline.png
    - assets/icons/reader-outline.png
    - assets/icons/resize-outline.png
    - assets/icons/rocket-outline.png
    - assets/icons/search-outline.png
    - assets/icons/shapes-outline.png
    - assets/icons/stats-chart-outline.png
    - assets/icons/tablet-landscape-outline.png
    - assets/icons/ticket-outline.png
    - assets/icons/toggle-outline.png
    - assets/icons/trending-up-outline.png
    - assets/icons/music-outline.png
    - assets/icons/newspaper-outline.png
    - assets/icons/shop-outline.png
    - assets/icons/hotel-outline.png
    - assets/icons/auth-outline.png
    - assets/icons/profile-outline.png
    - assets/icons/setting-outline.png
    - assets/icons/dashboard-outline.png
    - assets/icons/wallet-outline.png
    - assets/icons/chat-outline.png
    - assets/icons/email-outline.png
    - assets/icons/location-outline.png
    - assets/icons/food-outline.png
    - assets/icons/quiz-outline.png
    - assets/icons/school-outline.png
    - assets/icons/health-outline.png
    - assets/icons/worker.png

    #Other
    - assets/other/map-snap.png
    - assets/other/map-full-snap.png
    - assets/other/map-md-snap.png
    - assets/other/map-pin.png
    - assets/other/barcode.png

    #Designs
    - assets/design/pattern-1.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
